# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

root = Path(SPECPATH)

a = Analysis(
    [str(root / "run.py")],
    pathex=[str(root)],
    binaries=[],
    datas=[
        (str(root / "ui" / "dist"), "ui/dist"),
        (str(root / "hoplyra" / "images"), "hoplyra/images"),
    ],
    hiddenimports=[
        "hoplyra.desktop_env",
        "hoplyra.logging_config",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.http.h11_impl",
        "uvicorn.protocols.http.httptools_impl",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "uvicorn.lifespan.off",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.protocols.websockets.websockets_impl",
        "uvicorn.protocols.websockets.wsproto_impl",
        "uvicorn.protocols.websockets.websockets_sansio_impl",
        "uvicorn.protocols.utils",
        "uvicorn.main",
        "uvicorn.config",
        "uvicorn.server",
        "uvicorn.importer",
        "uvicorn.workers",
        "uvicorn._subprocess",
        "uvicorn._types",
        "uvicorn.middleware",
        "uvicorn.middleware.proxy_headers",
        "uvicorn.middleware.wsgi",
        "uvicorn.middleware.message_logger",
        "uvicorn.middleware.asgi2",
        "uvicorn.supervisors",
        "uvicorn.supervisors.basereload",
        "uvicorn.supervisors.multiprocess",
        "uvicorn.supervisors.statreload",
        "uvicorn.supervisors.watchfilesreload",
        "uvicorn.supervisors.watchgodreload",
        "uvicorn.supervisors.watchfilesreload",
        "anyio",
        "anyio._backends",
        "anyio._backends._asyncio",
        "paramiko",
        "cryptography",
        "cryptography.hazmat.primitives.kdf.pbkdf2",
        "itsdangerous",
        "multipart",
        "email_validator",
        "httptools",
        "websockets",
        "watchfiles",
        "h11",
        "click",
        "starlette.middleware.sessions",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="hoplyra-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
